server:
  port: 8082
spring:
  application:
    name: account-jdbc-amqp-sink
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
  cloud:
    function:
      definition: accountConsumer
    stream:
      function:
        bindings:
          bankAccountConsumer-in-0: input
          bankAccountConsumer-out-0: output
      binder:
        connection-name-prefix: ${spring.application.name}