apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-hub-user
  namespace: default
type: Opaque
stringData:
  username: hub
  password: hub
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: hub
  namespace: default
spec:
  tags:
    - administrator
  importCredentialsSecret:
    name: rabbitmq-hub-user
  rabbitmqClusterReference:
    name: rabbitmq-hub
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-hub-user-permission
  namespace: default
spec:
  vhost: "/"
  user: "hub" # name of the RabbitMQ user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq-hub