apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 3
  service:
    type: LoadBalancer
  image: rabbitmq:3.13-management
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 1Gi
  persistence:
    storage: 3Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
      - rabbitmq_shovel
      - rabbitmq_stream
      - rabbitmq_management
      - rabbitmq_stream_management
      - rabbitmq_stream_prometheus