apiVersion: v1
kind: Service
metadata:
  name: account-http-source-service
spec:
  selector:
    run:  account-http-source
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer