apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-prod
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-ca
  namespace: default
spec:
  ca:
    secretName: selfsigned-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert-ca
  namespace: default
spec:
  isCA: true
  dnsNames:
    - "*.tls-nodes.examples.svc.cluster.local"
  secretName: selfsigned-cert-ca
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-prod
    group: cert-manager.io
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: letsencrypt-ca
#  namespace: default
#spec:
#  isCA: true
#  commonName: osm-system
#  secretName: letsencrypt-ca
#  issuerRef:
#    name: letsencrypt-prod
#    kind: ClusterIssuer
#    group: cert-manager.io