apiVersion: v1
kind: Service
metadata:
  name: scdf-prometheus-proxy
  labels:
    app.kubernetes.io/name: spring-cloud-dataflow
    app.kubernetes.io/instance: scdf
    app.kubernetes.io/component: prometheus-proxy
  annotations:
    prometheus.io/path: /metrics/proxy
    prometheus.io/port: '8080'
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - name: rsocket
      port: 7001
      protocol: TCP
      targetPort: rsocket
  selector:
    app.kubernetes.io/name: spring-cloud-dataflow
    app.kubernetes.io/instance: scdf
    app.kubernetes.io/component: prometheus-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scdf-prometheus-proxy
  labels:
    app.kubernetes.io/name: spring-cloud-dataflow
    app.kubernetes.io/instance: scdf
    app.kubernetes.io/component: prometheus-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-cloud-dataflow
      app.kubernetes.io/instance: scdf
      app.kubernetes.io/component: prometheus-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-cloud-dataflow
        app.kubernetes.io/instance: scdf
        app.kubernetes.io/component: prometheus-proxy
    spec:      
      serviceAccountName: scdf-data-flow
      containers:
        - name: prometheus-proxy
          image: docker.io/bitnami/prometheus-rsocket-proxy:1.2.1-debian-10-r38
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: rsocket
              containerPort: 7001
              protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scdf-spring-cloud-dataflow-prometheus-proxy
  labels:
    app.kubernetes.io/name: spring-cloud-dataflow
    app.kubernetes.io/instance: scdf
    app.kubernetes.io/component: prometheus-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-cloud-dataflow
      app.kubernetes.io/instance: scdf
      app.kubernetes.io/component: prometheus-proxy
  endpoints:
    - port: http
      path: "/metrics/connected"
    - port: http
      path: "/metrics/proxy"
  namespaceSelector:
    matchNames:
      - default
