server:
  port: 8081
spring:
  application:
    name: account-geode-sink
  cloud:
    function.definition: accountConsumer
    stream:
      bindings:
        accountConsumer-in-0:
          destination: banking.account
          group: bankingAccountStream
          consumer:
            concurrency: 20
            container-type: stream
      rabbit:
        bindings:
          accountConsumer-in-0:
            consumer:
              container-type: stream

  rabbitmq:
    listener:
      type: stream
    stream:
      host: localhost