server:
  port: 8081
  application:
    name: account-geode-sink
  cloud:
    function.definition: accountConsumer
    stream:
      bindings:
        accountConsumer-in-0:
          destination: banking.account
          group: bankingAccount
          consumer:
            concurrency: 20
      rabbit:
        bindings:
          accountConsumer-in-0:
            consumer:
              autoBindDlq: true
              quorum.enabled: true
              dlqQuorum:
                enabled: true
              prefetch: 10000
#        default:
#          quorum.enabled: true
#          autoBindDlq: true