apiVersion: rabbitmq.tanzu.vmware.com/v1beta1
kind: StandbyReplication
metadata:
  name: upstream-configuration
spec:
  operatingMode: "upstream" # has to be "upstream" to configure an upstream RabbitMQ cluster; required value
  upstreamModeConfiguration: # list of policies that Operator will create
    replicationPolicies:
      - name: all-policy # policy name; required value
        pattern: "^.*" # any regex expression that will be used to match quorum queues name; required value
        vhost: "rabbitmq_schema_definition_sync" # vhost name; must be an existing vhost; required value
  rabbitmqClusterReference:
    name: rabbit-hare # the upstream RabbitMQ cluster name; must be in the same namespace; required value
---
apiVersion: rabbitmq.tanzu.vmware.com/v1beta1
kind: StandbyReplication
metadata:
  name: downstream-configuration
spec:
  operatingMode: "downstream" # has to be "downstream" to configure an downstream RabbitMQ cluster
  downstreamModeConfiguration:
    endpoints: "rabbit-hare:5552" # comma separated list of endpoints to the upstream RabbitMQ
    upstreamSecret:
      name: ha-users # an existing Kubernetes secret; required value
  rabbitmqClusterReference:
    name:  rabbit-bunny # RabbitMQ cluster name; must be in the same namespace; required value