apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tanzu-rabbitmq-registry-creds    # must match source secret name
  namespace: default                 # must match source secret namespace
spec:
  toNamespaces:
    - "*"  # star means export is available for all namespaces