apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: gemfire-management-console
    run:  gemfire-management-console
  name:  gemfire-management-console
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  gemfire-management-console
  template:
    metadata:
      labels:
        name:  gemfire-management-console
    spec:
      containers:
        - env:
            - name: server.port
              value: "8080"
          image: gemfire/gemfire-management-console:1.2
          name: gemfire-management-console
#          imagePullPolicy: Always
#          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: gemfire-management-console
spec:
  selector:
    name: gemfire-management-console
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer