apiVersion: v1
kind: Secret
metadata:
  name: rabbit-app-secret
type: Opaque
stringData:
  username: app
  password: changeme
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbit-app-user
spec:
  tags:
  - administrator # available tags are 'management', 'policymaker', 'monitoring' and 'administrator'
  rabbitmqClusterReference:
    name: rabbitmq # rabbitmqCluster must exist in the same namespace as this resource
  importCredentialsSecret:
    name: rabbit-app-secret
