server:
  port: 8081
spring:
  application:
    name: account-gemfire-amqp-sink
  cloud:
    function.definition: accountConsumer
    stream:
      bindings:
        accountConsumer-in-0:
          destination: event-streaming-showcase
          group: stream-account-gemfire-sink
          consumer:
            concurrency: 1
      rabbit:
        bindings:
          accountConsumer-in-0:
            consumer:
              autoBindDlq: true
              quorum.enabled: true
              dlqQuorum:
                enabled: true
              prefetch: 10000

  data:
    gemfire:
      pool:
        locators: localhost[10334]
#        default:
#          quorum.enabled: true
#          autoBindDlq: true