apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run:  vehicles-geode-sink
  name:  vehicles-geode-sink
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  vehicles-geode-sink
  template:
    metadata:
      labels:
        name:  vehicles-geode-sink
    spec:
      containers:
        - env:
            - name: spring.cloud.stream.bindings.vehicleGemFireSink-in-0.consumer.concurrency
              value: "5"
            - name: spring.rabbitmq.host
              value: rabbitmq
            - name: spring_rabbitmq_username
              valueFrom:
                secretKeyRef:
                  name: vehicle-secrets
                  key: spring_rabbitmq_username
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  name: vehicle-secrets
                  key: spring_rabbitmq_password
            - name: spring.data.gemfire.pool.locators
              valueFrom:
                configMapKeyRef:
                  name: vehicle-configmap
                  key: spring.data.gemfire.pool.locators
          image: nyla/vehicles-geode-sink:0.0.1-SNAPSHOT
          name: vehicles-geode-sink
