apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    component: master
  annotations:
    prometheus.io/port: '9104'
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      nodePort: null
  selector:
    app: mysql
    component: master
