version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  ignore:
    - dependency-name: "k8s.io/api"
      versions: ["0.19.x"]
    - dependency-name: "k8s.io/api-machinery"
      versions: ["0.19.x"]
    - dependency-name: "k8s.io/client-go"
      versions: ["0.19.x"]
    - dependency-name: "github.com/go-logr/logr"
      versions: ["0.2.x"]
