# More on fanout exchange and other exchange types, see: https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchanges.
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: pos.products
spec:
  name: pos.products # name of the exchange
  vhost: "/" # default to '/' if not provided
  type: topic # default to 'direct' if not provided
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq # rabbitmqCluster must exist in the same namespace as this resource
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: pos.products.consumer
spec:
  name: pos.products.consumer # name of the queue
  vhost: "/" # default to '/' if not provided
  type: quorum # without providing a queue type, rabbitmq creates a classic queue
  autoDelete: false
  durable: true # seting 'durable' to false means this queue won't survive a server restart
  rabbitmqClusterReference:
    name: rabbitmq # rabbitmqCluster must exist in the same namespace as this resource
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: pos.products
spec:
  vhost: "/" # default to '/' if not provided
  source: pos.products # an existing exchange
  destination: pos.products.consumer # an existing queue or exchange
  destinationType: queue # can be 'queue' or 'exchange'
  routingKey: "#"
  rabbitmqClusterReference:
    name: rabbitmq # rabbitmqCluster must exist in the same namespace as this resource
