server:
  port: 0
spring:
  application:
    name: jdbc-sql-processor
  jpa:
    show-sql: true
  cloud:
    function:
      definition: sqlQueryProcessor
    stream:
      function:
        bindings:
          sqlQueryProcessor-in-0: input
          sqlQueryProcessor-out-0: output
      binder:
        connection-name-prefix: ${spring.application.name}