server:
  port: 0
spring:
  application:
    name: jdbc-sql-processor
  jpa:
    show-sql: true
  cloud:
    function:
      definition: sqlQueryConsumer
    stream:
      function:
        bindings:
          sqlQueryConsumer-in-0: input
      binder:
        connection-name-prefix: ${spring.application.name}