#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata":{"name": "rabbitmq-cluster-operator"}}), expects="1+"
---
spec:
  template:
    spec:
      containers:
        #@overlay/match by="name", expects="1+"
        - name: operator
          image: #@ data.values.operator_image

