apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run:  gemfire-sink-app
  name:  gemfire-sink-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  gemfire-sink-app
  template:
    metadata:
      labels:
        name:  gemfire-sink-app
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-java: "opentelemetry-operator-system/otelinst"

    spec:
      containers:
        - env:
            - name: server.port
              value: "8080"
            - name: regionName
              value: Event
            - name: spring.application.name
              value: gemfire-sink-app
            - name: spring.rabbitmq.host
              value: rabbitmq-site3
            - name: spring.rabbitmq.stream.host
              value: rabbitmq-site3
            - name: spring.rabbitmq.username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-site3-user
                  key: username
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-site3-user
                  key: password
            - name: spring.data.gemfire.pool.locators
              valueFrom:
                configMapKeyRef:
                  name: gemfire1-config
                  key: locators
            - name: keyFieldExpression
              value: "id"
            - name: valuePdxClassName
              value: "demo.logistics.domain.Event"
            - name: cluster
              value: site3
            - name: spring.cloud.stream.bindings.gemFireSinkConsumer-in-0.destination
              value: event-exchange
            - name: spring.cloud.stream.bindings.gemFireSinkConsumer-in-0.group
              value: gemfire-event
            - name: spring.cloud.stream.rabbit.bindings.input.consumer.quorum.enabled
              value: "true"
            - name: spring.cloud.stream.rabbit.bindings.input.consumer.bindingRoutingKey
              value: "#"
#            - name: management.wavefront.api-token
#              valueFrom:
#                secretKeyRef:
#                  name: wavefront-secret
#                  key: management.wavefront.api-token
#            - name: management.wavefront.uri
#              value: proxy://wavefront-proxy.observability-system.svc.cluster.local:2878
            - name: management.wavefront.application.name
              value: gemfire-sink-app
            - name: management.wavefront.application.service-name
              value: gemfire-sink-app
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60 #wait seconds before performing the first probe
            periodSeconds: 5 #pecifies that the kubelet should perform a liveness probe every 3 seconds
            timeoutSeconds: 10 # Number of seconds after which the probe times out.
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60 #wait seconds before performing the first probe
            periodSeconds: 5 #pecifies that the kubelet should perform a liveness probe every 3 seconds
            timeoutSeconds: 10 # Number of seconds after which the probe times out.
            failureThreshold: 60
          image: cloudnativedata/gemfire-sink-app:0.0.2-SNAPSHOT
          name: gemfire-sink-app