apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run:  geode-sink-rabbit
  name:  geode-sink-rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  geode-sink-rabbit
  template:
    metadata:
      labels:
        name:  geode-sink-rabbit
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-java: "opentelemetry-operator-system/otelinst"

    spec:
      containers:
        - env:
            - name: server.port
              value: "8080"
            - name: geode.consumer.json
              value: "true"
            - name: geode.pool.connect-type
              value: locator
            - name: geode.region.region-name
              value: Event
            - name: spring.application.name
              value: geode-sink-rabbit
            - name: spring.rabbitmq.host
              value: rabbitmq-site3
            - name: spring.rabbitmq.stream.host
              value: rabbitmq-site3
            - name: spring.rabbitmq.username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-site3-user
                  key: username
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-site3-user
                  key: password
            - name: spring.data.gemfire.pool.locators
              valueFrom:
                configMapKeyRef:
                  name: gemfire1-config
                  key: locators
            - name: geode.pool.host-addresses
              value: "gemfire1-locator:10334"
            - name: geode.consumer.keyExpression
              value: "payload.getField('id')"
            - name: spring.cloud.stream.bindings.input.destination
              value: event-exchange
            - name: spring.cloud.stream.bindings.input.group
              value: gemfire-event
            - name: spring.cloud.stream.rabbit.bindings.input.consumer.quorum.enabled
              value: "true"
            - name: spring.cloud.stream.rabbit.bindings.input.consumer.bindingRoutingKey
              value: "#"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60 #wait seconds before performing the first probe
            periodSeconds: 5 #pecifies that the kubelet should perform a liveness probe every 3 seconds
            timeoutSeconds: 10 # Number of seconds after which the probe times out.
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60 #wait seconds before performing the first probe
            periodSeconds: 5 #pecifies that the kubelet should perform a liveness probe every 3 seconds
            timeoutSeconds: 10 # Number of seconds after which the probe times out.
            failureThreshold: 60
          image: springcloudstream/geode-sink-rabbit:3.2.1
          name: geode-sink-rabbit