apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-site1
spec:
  replicas: 1
  service:
    type: LoadBalancer
  image: rabbitmq:3.13.1-management
  resources:
    requests:
      cpu: "0.5"
      memory: "1Gi"
    limits:
      cpu: "0.5"
      memory: "1Gi"
  imagePullSecrets:
    - name: tanzu-rabbitmq-registry-creds
  rabbitmq:
    additionalPlugins:
      - rabbitmq_stream
      - rabbitmq_stream_management
      - rabbitmq_shovel
      - rabbitmq_shovel_management
      - rabbitmq_federation_management
      - rabbitmq_mqtt
      - rabbitmq_prometheus
      - rabbitmq_peer_discovery_k8s