apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-site3-user
type: Opaque
stringData:
  username: site3
  password: site3
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: site3
spec:
  tags:
    - administrator
  importCredentialsSecret:
    name: rabbitmq-site3-user
  rabbitmqClusterReference:
    name: rabbitmq-site3
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-site3-user-permission
spec:
  vhost: "/"
  user: "site3" # name of the RabbitMQ user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq-site3