apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-site1-user
type: Opaque
stringData:
  username: site1
  password: changeme
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: site1
spec:
  tags:
    - administrator
  importCredentialsSecret:
    name: rabbitmq-site1-user
  rabbitmqClusterReference:
    name: rabbitmq-site1
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-site1-user-permission
  namespace: default
spec:
  vhost: "/"
  user: "site1" # name of the RabbitMQ user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq-site1