apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: site3-event-queue # name of this custom resource; does not have to the same as the actual queue name
spec:
  name: event-queue # name of the queue
  vhost: "/" # default to '/' if not provided
  type: quorum # without providing a queue type, rabbitmq creates a classic queue
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq-site3
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name:  site3-event-exchange
spec:
  name: event-exchange # name of the exchange
  type: topic # default to 'direct' if not provided; can be set to 'direct', 'fanout', 'headers', and 'topic'
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq-site3
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name:  site3-event-binding
spec:
  source: event-exchange # an existing exchange
  destination: event-queue # an existing queue
  destinationType: queue # can be 'queue' or 'exchange'
  routingKey: "#"
  rabbitmqClusterReference:
    name: rabbitmq-site3