apiVersion: v1
kind: Secret
metadata:
  name: site1-to-hub-secret
type: Opaque
stringData:
  srcUri: "amqp://"
  destUri: "amqp://hub:changeme@rabbitmq-hub:5672"
---
apiVersion: rabbitmq.com/v1beta1
kind: Shovel
metadata:
  name: site1-to-hub
spec:
  name: "site1-to-hub"
  uriSecret:
    # secret must be created in the same namespace as this Shovel object; in this case 'rabbitmq-system'
    name: site1-to-hub-secret
  srcQueue: "event-queue"
  destExchange: "event-exchange"
  rabbitmqClusterReference:
    name: rabbitmq-site1