apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run:  account-rest-service
  name:  account-rest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  account-rest-service
  template:
    metadata:
      labels:
        name:  account-rest-service
    spec:
      containers:
        - env:
            - name: spring.profiles.active
              value: stream
            - name: gemfire.region.name
              value: AccountStream
            - name: spring.rabbitmq.host
              value: rabbitmq
            - name: spring_rabbitmq_username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
          image: account-rest-service:0.0.1-SNAPSHOT
          name: account-rest-service
