spring:
  application:
    name: api-throttling
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    function:
      definition: apiThrottleConsumer
    stream:
      function:
        bindings:
          apiThrottleConsumer-in-0: input
          apiThrottleConsumer-out-0: output