account:
  generate:
    count: 100000
server:
  port: 0
spring:
  rabbitmq:
    publisher-confirm-type: simple
  application:
    name: account-generator-streams-source
  cloud:
    function.definition: accountGeneratorSupplier
    stream:
      bindings:
        accountGeneratorSupplier-out-0:
          destination: event-streaming-showcase
      rabbit:
        default:
          quorum.enabled: true