apiVersion: gemfire.vmware.com/v1
kind: GemFireCluster
metadata:
  name: gemfire1
  namespace: default
spec:
  ingress:
    gatewayName: gf-gateway
  image: registry.pivotal.io/pivotal-gemfire/vmware-gemfire:10.1.1
  security:
    tls: {}
  metrics:
    emission: Default
  locators:
    replicas: 1
    resources:
      requests:
        memory: 1Gi
    persistentVolumeClaim:
      deleteOnShutdown: true
  servers:
    replicas: 1
    resources:
      requests:
        memory: 1Gi
    persistentVolumeClaim:
      deleteOnShutdown: true
---
apiVersion: v1
kind: Service
metadata:
  name: gemfire-locator
spec:
  selector:
    gemfire.vmware.com/app: gemfire1-locator
  ports:
    - name: management
      port: 7070
      targetPort: 7070
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: LoadBalancer